### ISSUE TITLE
DevExpress.Blazor.Dashboard 

### ISSUE THREAD

**Issue by PackFan2019** [DevExpress-Examples/dashboard-blazor-server-app#1]
I just tried Free Trial Feed URL for 30 days on Dev Express.  It looks like that that URL could find all packages on 21.1.2-beta such as DevExpress.AspNetCore.Dashboard except for DevExpress.Blazor.Dashboard.   

Do you happen to know how we could find DevExpress.Blazor.Dashboard on 21.1.2-beta through 30 free trial? Thanks.

**Comment by Stason4eg** [comment]
Hello,

The thing is that we do not have a trial period for our EAP/Beta versions. Thus, you can't get the Blazor Dashboard package. The only way is to wait for the official release and get the trial period.

You can buy the Universal subscription to be able to use our Beta version and test the new Dashboard component for Blazor. If you are not satisfied with our tools for any reason, you can request a refund within your first 60 days of ownership.

If you have any technical questions, feel free to ask them in our Support Center - [https://supportcenter.devexpress.com/ticket/create](https://supportcenter.devexpress.com/ticket/create). We will be happy to follow up with you.
